#spring:
#  profiles:
#    active: dev 
#  
#
#management:
# endpoints:
#  web:
#   exposure:
#    include: "*"

#    
#server:
#  port: 8080
#  
#  
#logging:
#  file: Errorlog.log
#  level:
#    root: error
#  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss,SSS} %5p [%t] %c [%M] - %m%n"
#    
#
#---  
#spring:      
#  profiles: dev
#  
#  datasource:    
#    url: jdbc:mysql://localhost:3306/sample
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 
#    initialization-mode: always
#
#  jpa:
#   properties:
#    hibernate.dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#    database: MYSQL
#    hibernate:
#     ddl-auto: create
#
#
